#!/usr/bin/env python3
"""Regenerate every output in the Fletcher / Mulrooney manuscript.

    python reproduce.py                      # compute, write results/, draw figures
    python reproduce.py --sync-manuscript    # also copy figures into ../manuscript/figures
    python verify_against_paper.py           # then check results against the paper

Outputs (all under results/):
    results.json                  every statistic, table value and in-text number
    paper_numbers.md              the same numbers, labelled by where they appear in the paper
    tables/table1_quartiles.*     Table 1 as CSV and as LaTeX rows
    tables/table2_metros.*        Table 2 as CSV and as LaTeX rows
    tables/density_quartiles.csv  access by population-density quartile
    figures/fig1..fig3 *.png      the three figures
    environment.txt               package versions used for this run
"""
from __future__ import annotations

import argparse
import json
import platform
import shutil
import sys
from pathlib import Path

import pandas as pd

import analysis
import figures

HERE = Path(__file__).resolve().parent
DEFAULT_INPUT = HERE.parent / "outputs" / "streamlit_queries" / "nc_usa"


def latex_tables(res):
    st = res["statewide"]
    labels = {"Q1": "Q1 (lowest \\% Black)", "Q2": "Q2", "Q3": "Q3", "Q4": "Q4 (highest \\% Black)"}
    t1 = [f"{labels[q['quartile']]} & {q['tracts']} & {q['median_nearest_km']} & "
          f"{q['mean_stores_5km']:.2f} & {q['pct_no_store_5km']} \\\\" for q in res["quartiles"]]
    n_state = f"{st['tracts']:,}".replace(",", "{,}")
    t2 = [f"North Carolina & {n_state} & {st['median_pct_black']} & {st['nearest_km_median']} & "
          f"{st['pct_no_store_5km']} & {st['mean_stores_5km']:.2f} & {res['moran']['nearest_store_km']['I']:.2f} \\\\"]
    for m in res["metros"]:
        t2.append(f"{m['metro']} & {m['tracts']} & {m['median_pct_black']} & {m['median_nearest_km']} & "
                  f"{m['pct_no_store_5km']} & {m['mean_stores_5km']:.2f} & {m['moran_I_distance']:.2f} \\\\")
    return "\n".join(t1) + "\n", "\n".join(t2) + "\n"


def numbers_sheet(res):
    s, mo, sp, nb = res["statewide"], res["moran"], res["spearman"], res["negative_binomial"]
    q, d = res["quartiles"], res["density_quartiles"]
    t = nb["terms"]
    L = [
        "# Numbers in the paper, and where they come from", "",
        "Generated by `reproduce.py`. Do not edit by hand.", "",
        "## Abstract and Results 3.1 (statewide access)",
        f"- Tracts analysed: {s['tracts']:,} ({s['zero_population_tracts_excluded']} zero-population tracts of {s['tracts_in_file']:,} excluded)",
        f"- Population: {s['population']:,}",
        f"- Stores in the OpenStreetMap extract: {s['stores_in_extract']}; strictly inside NC: {s['stores_inside_state']}; "
        f"inside NC or within about 8 km of it (mapped in Fig. 1): {s['stores_mapped_within_8km_of_state']}; "
        f"farther outside: {s['stores_outside_state']}",
        f"- Tracts with no store within 5 km: {s['tracts_no_store_5km']:,} ({s['pct_no_store_5km']}%)",
        f"- Median distance to nearest store: {s['nearest_km_median']} km (IQR {s['nearest_km_q1']} to {s['nearest_km_q3']})",
        f"- Median tract percent Black: {s['median_pct_black']}%", "",
        "## Results 3.2 (spatial clustering, Moran's I, queen contiguity, "
        f"{res['settings']['permutations']} permutations, seed {res['settings']['seed']})",
        f"- Nearest-store distance: I = {mo['nearest_store_km']['I']:.3f}, pseudo-p = {mo['nearest_store_km']['p']}",
        f"- Store count within 5 km: I = {mo['store_count_5km']['I']:.3f}, pseudo-p = {mo['store_count_5km']['p']}",
        f"- Percent Black: I = {mo['pct_black']['I']:.3f}, pseudo-p = {mo['pct_black']['p']}", "",
        "## Results 3.3 (Table 1 and Figure 2)",
    ]
    for r in q:
        L.append(f"- {r['quartile']} ({r['pct_black_min']} to {r['pct_black_max']}% Black, n={r['tracts']}): "
                 f"median nearest {r['median_nearest_km']} km, mean stores within 5 km {r['mean_stores_5km']}, "
                 f"{r['pct_no_store_5km']}% with none")
    L += [
        f"- Spearman rho, percent Black vs nearest-store distance: {sp['pct_black_vs_nearest_km']['rho']:.3f}",
        f"- Spearman rho, percent Black vs store count: {sp['pct_black_vs_store_count_5km']['rho']:.3f}",
        f"- Negative binomial GLM (n={nb['n']}, dispersion fixed at alpha=1): IRR percent Black "
        f"{t['pct_black']['irr']:.3f} (p={t['pct_black']['p']:.1e}); poverty {t['poverty_rate']['irr']:.3f} "
        f"(p={t['poverty_rate']['p']:.1e}); income per $10k {t['inc10k']['irr']:.3f} (p={t['inc10k']['p']:.1e})",
    ]
    sa = nb.get("sensitivity_estimated_alpha", {})
    if "alpha" in sa:
        L.append(f"- Sensitivity, dispersion estimated (alpha={sa['alpha']:.2f}): IRR percent Black "
                 f"{sa['terms']['pct_black']['irr']:.3f}, poverty {sa['terms']['poverty_rate']['irr']:.3f}, "
                 f"income {sa['terms']['inc10k']['irr']:.3f}; all p < 0.001: "
                 f"{all(v['p'] < 0.001 for v in sa['terms'].values())}")
    sc = nb.get("sensitivity_county_clustered_se", {})
    if "terms" in sc:
        L.append("- Sensitivity, county-clustered standard errors: IRRs "
                 f"{sc['terms']['pct_black']['irr']:.3f} / {sc['terms']['poverty_rate']['irr']:.3f} / "
                 f"{sc['terms']['inc10k']['irr']:.3f}; all p < 0.001: {all(v['p'] < 0.001 for v in sc['terms'].values())}")
    L += ["", "## Results 3.3 (population density, the urban to rural check)"]
    for r in d:
        L.append(f"- {r['quartile']} (median {r['median_density_per_km2']:.0f} persons/km2, n={r['tracts']}): "
                 f"median nearest {r['median_nearest_km']} km, {r['pct_no_store_5km']}% with no store within 5 km")
    L += ["", "## Results 3.4 (Table 2, Figure 3; Moran's I is for nearest-store distance)"]
    for m in res["metros"]:
        L.append(f"- {m['metro']}: {m['tracts']} tracts, median Black {m['median_pct_black']}%, nearest {m['median_nearest_km']} km, "
                 f"{m['pct_no_store_5km']}% none within 5 km, mean stores {m['mean_stores_5km']}, I={m['moran_I_distance']:.2f}; "
                 f"majority-Black tracts nearest {m['nearest_km_majority_black']} km vs other {m['nearest_km_other']} km")
    L.append(f"- Moran's I across metros: {res['metro_moran_range'][0]:.2f} to {res['metro_moran_range'][1]:.2f}")
    return "\n".join(L) + "\n"


def environment_text():
    import esda, geopandas, libpysal, matplotlib, numpy, scipy, shapely, statsmodels
    rows = [("python", platform.python_version())] + [
        (m.__name__, m.__version__) for m in
        (pd, numpy, scipy, geopandas, shapely, libpysal, esda, statsmodels, matplotlib)]
    return "\n".join(f"{n}=={v}" for n, v in rows) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT,
                    help="folder holding beauty_access_enriched.geojson and beauty_supply_stores.geojson")
    ap.add_argument("--out-dir", type=Path, default=HERE / "results")
    ap.add_argument("--permutations", type=int, default=999)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--sync-manuscript", action="store_true",
                    help="copy the figures into ../manuscript/figures so the paper compiles with them")
    args = ap.parse_args(argv)

    for name in ("beauty_access_enriched.geojson", "beauty_supply_stores.geojson"):
        if not (args.input_dir / name).exists():
            sys.exit(f"Missing input: {args.input_dir / name}\nSee README.md, section 'Inputs'.")

    print(f"Reading {args.input_dir}")
    res, tracts, strict, mapped = analysis.compute_all(args.input_dir, args.permutations, args.seed)
    res["inputs"] = {"directory": str(args.input_dir.relative_to(HERE.parent)
                                      if args.input_dir.is_relative_to(HERE.parent) else args.input_dir)}

    out = args.out_dir
    (out / "tables").mkdir(parents=True, exist_ok=True)
    (out / "results.json").write_text(json.dumps(res, indent=2))
    pd.DataFrame(res["quartiles"]).to_csv(out / "tables" / "table1_quartiles.csv", index=False)
    pd.DataFrame(res["metros"]).to_csv(out / "tables" / "table2_metros.csv", index=False)
    pd.DataFrame(res["density_quartiles"]).to_csv(out / "tables" / "density_quartiles.csv", index=False)
    t1, t2 = latex_tables(res)
    (out / "tables" / "table1_quartiles_rows.tex").write_text(t1)
    (out / "tables" / "table2_metros_rows.tex").write_text(t2)
    (out / "paper_numbers.md").write_text(numbers_sheet(res))
    (out / "environment.txt").write_text(environment_text())

    names = figures.make_all(tracts, mapped, res, out / "figures")
    print("Wrote:", ", ".join(["results.json", "paper_numbers.md", "tables/*"] + names))

    if args.sync_manuscript:
        dest = HERE.parent / "manuscript" / "figures"
        dest.mkdir(parents=True, exist_ok=True)
        for n in names:
            shutil.copy2(out / "figures" / n, dest / n)
        print(f"Copied figures to {dest.relative_to(HERE.parent)}")
    print("Next: python verify_against_paper.py")


if __name__ == "__main__":
    main()
